### ISSUE TITLE
Unhandled Exception: System.MissingMethodException: Cannot create an instance of an interface.

### ISSUE THREAD

**Issue by ma6254** [VeroFess/QQBot#7]
```cmd
C:\Users\mjc\git\QQBot (master)
λ dotnet .\ChatBotFramework\bin\Debug\netcoreapp2.0\ChatBotFramework.dll
Begin Initialize ...
Add new autoload class to list :ChatBotFramework.InstanceHelper.AppInstance.Interfaces.IAutoLoad
begin invoke autoload class: ChatBotFramework.InstanceHelper.AppInstance.Interfaces.IAutoLoad

Unhandled Exception: System.MissingMethodException: Cannot create an instance of an interface.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at ChatBotFramework.InstanceHelper.AppInstance.AppEntry.InvokeAutoLoad(Type _Class) in C:\Users\mjc\git\QQBot\ChatBotFramework\InstanceHelper\AppInstance\AppEntry.cs:line 15
   at ChatBotFramework.InstanceHelper.AppInstance.AppEntry.InitializeApplication() in C:\Users\mjc\git\QQBot\ChatBotFramework\InstanceHelper\AppInstance\AppEntry.cs:line 49
   at ChatBotFramework.BotInstance.Main(String[] args) in C:\Users\mjc\git\QQBot\ChatBotFramework\BotInstance.cs:line 36
^C
```

**Comment by VeroFess** [comment]
旧版以废弃,请等待新版更新
